general:
  # The interval at which instances are checked as to whether they should be removed, or if additional ones should be added
  tick-interval: 1min
  # How many initial instances for each map is generated. Additional instances may be created if cap is reached
  initial-instances: 1
  # Maximum amount of instances
  max-instances: 4
  breakable-blocks:
    - coal_ore
    - copper_ore
    - iron_ore
    - gold_ore
    - redstone_ore
    - emerald_ore
    - lapis_ore
    - diamond_ore
    - deepslate_coal_ore
    - deepslate_copper_ore
    - deepslate_iron_ore
    - deepslate_gold_ore
    - deepslate_redstone_ore
    - deepslate_emerald_ore
    - deepslate_lapis_ore
    - deepslate_diamond_ore
  overhanging-blocks: ["oak_leaves", "spruce_leaves", "acacia_leaves", "birch_leaves", "jungle_leaves", "dark_oak_leaves"]
  # Commands executed for each player joining the event. Use the @player tag to replace it
  # with the player's name.
  on-join-expedition-commands:
    - 'tellraw @player {"text":"Information about the event; You have only so much time to gather resources and loot before the second phase. Once the second phase begins you must make your way to an extraction zone before time runs out!","color":"gray"}'
  # How much time does it take to extract once started.
  extraction-time: 10s
  # The block to use for loot chests
  loot-chest-block: chest
  # If something goes wrong and a player has joined an expedition world when they aren't supposed to, teleport them to
  # this location
  fallback-location: 0,60,0
  fallback-world: Lobby
  # The allowed commands whilst in an expedition unless you have the permission expeditions.admin.bypass
  allowed-commands:
    - party
loot-tables: # Loot tables used by maps are specified here.
  common_crate: # Unique identifier for this loot table
    quantity: 1-3 # Can be a single number, or a range such as 3-4 or 3to4. Represents the amount of loot types given.
    loot:
    - id: 'mmoitem:sword:ancient_sword'
      quantity: 1 # Can be a single number, or a range such as 3-4 or 3to4
      weight: 1 # The higher the weight, the higher the chance of rolling
    - id: 'vanilla:gold_ingot'
      quantity: 3-4
      weight: 5
    - id: 'vanilla:rotten_flesh'
      quantity: 3-4
      weight: 5
