general:
  # The interval at which instances are checked as to whether they should be removed, or if additional ones should be added
  tick-interval: 1min
  # How many initial instances for each map is generated. Additional instances may be created if cap is reached
  initial-instances: 1
  # Maximum amount of instances
  max-instances: 4
  breakable-blocks:
    - coal_ore
    - copper_ore
    - iron_ore
    - gold_ore
    - redstone_ore
    - emerald_ore
    - lapis_ore
    - diamond_ore
    - deepslate_coal_ore
    - deepslate_copper_ore
    - deepslate_iron_ore
    - deepslate_gold_ore
    - deepslate_redstone_ore
    - deepslate_emerald_ore
    - deepslate_lapis_ore
    - deepslate_diamond_ore
  overhanging-blocks: ["oak_leaves", "spruce_leaves", "acacia_leaves", "birch_leaves", "jungle_leaves", "dark_oak_leaves"]
  # How much time does it take to extract once started.
  extraction-time: 10s
  # The block to use for loot chests
  loot-chest-block: chest
  # If something goes wrong and a player has joined an expedition world when they aren't supposed to, teleport them to
  # this location
  fallback-location: 0,60,0
  fallback-world: Lobby
  # The allowed commands whilst in an expedition unless you have the permission expeditions.admin.bypass
  allowed-commands:
    - party
